### ISSUE TITLE
Add support for a single frontend and multiple backends

### ISSUE THREAD

**Issue by ianrossi** [sous-chefs/haproxy#111]
I just wrote a wrapper cookbook that will accomplish this. It uses most of what is already in the haproxy cookbook and does some additional things with attributes. Do you think there is an interest to have this option in the upstream cookbook? I could fork it and setup a PR. It could basically offer an option specify an array of app roles instead of just one.

My _discovery recipes does the same thing as the current _discovery except it iterates additionally through an array of app roles. Then my wrapper's default recipe sets up the frontend and backends with the LWRPs.

I imagine there are others that want to use one load balancer in front of multiple different app clusters. We're doing this currently in our infrastructure because it means less nodes to manage. If we load balanced each app cluster, we would have 7 load balancers.

**Comment by damacus** [comment]
@ianrossi thanks!

We're moving towards custom resources. Feel free to take a look at the #164 PR and see if that meets your needs. It if doesn't I'd love some feedback. 


Cheers
Dan
