### ISSUE TITLE
Service fails to start when installing from source with systemd

### ISSUE THREAD

**Issue by lmickh** [sous-chefs/haproxy#113]
When installing from source on Debian 8, the service will fail to start because systemd does not recognize it.  Have not tested other systemd distros yet.  Would assume it does.

Running `systemctl daemon-reload` works with the current init.d script or a systemd unit file could be generated instead.  Would require a platform version check either way.

**Comment by rshade** [comment]
can you see if this is still a problem in the 3.x release?
