### ISSUE TITLE
Service reload/restart can cause multiple instances of haproxy process

### ISSUE THREAD

**Issue by kcd83** [sous-chefs/haproxy#114]
The restart and reload logic in the CentOS service script (`templates/centos/haproxy-init.erb`) doesn't have enough locking and can result in multiple haproxy processes. It is very easy to reproduce

```
service haproxy reload & service haproxy reload
```

or

```
service haproxy restart & service haproxy restart
```

The problem is most likely to arise when you have automated logic to reload as the configuration changes.

**Comment by rshade** [comment]
I see this is closed in the consul-template, is this fixed on your side @kcd83

**Comment by kcd83** [comment]
I no longer have this setup but yes I believe it did
