### ISSUE TITLE
ordering of configuration

### ISSUE THREAD

**Issue by sdarwin** [sous-chefs/haproxy#119]
Inside an haproxy backend, you might have "default-server" and also "server".   It turns out these are order dependent, and "default-server" must go first.

However, the haproxy_lb provider in the cookbook prints out servers first, and then params.   default-server is (or could be) a customized param, and so the results are out-of-order.     

A code fix is to move params to the beginning, or servers to the end, in the file providers/lb.rb

**Comment by damacus** [comment]
This is definitely fixed in #164 ! Thanks for the information
