### ISSUE TITLE
cookie support

### ISSUE THREAD

**Issue by sdarwin** [sous-chefs/haproxy#120]
For the cookie functionality to work, each "server" must specify a cookie.

The commit on Aug 24, 2013 entitled "[COOK-3237] Add node['haproxy']['cookie'] to set a cookie …" correctly added these extra options to each "server" entry in templates/default/haproxy.cfg.erb:

check <% if node['haproxy']['cookie'] %>cookie <%= member['hostname'] %><% end %>

Great.  Although, why it was added to http servers and not to https servers is a bit of a mystery and perhaps an omission?

Then the commit on Sept 25, 2013 "Make lb provider more generic", the code was relocated to default.rb recipe, and the cookie section removed.   

That code, of "check <% if node['haproxy']['cookie'] %>cookie <%= member['hostname'] %><% end %>" should be added back to each server line in recipes/manual.rb  ,  unless I am missing something here.

**Comment by rshade** [comment]
is this fixed here: https://github.com/sous-chefs/haproxy/blob/master/recipes/manual.rb#L84?

**Comment by sdarwin** [comment]
Search for the text "<% if node['haproxy']['cookie'] %>" in this commit https://github.com/sous-chefs/haproxy/commit/37bab56918aab215cf6d64b20df1bdb4116fc350  ,  and notice in the three cases it then adds "member['hostname']"  to each server.  Not sure if the newest commit makes the same change.  
From the earlier comment, I believe this code "check <% if node['haproxy']['cookie'] %>cookie <%= member['hostname'] %><% end %>" should be added back to each server line, as in the original.

**Comment by rshade** [comment]
we released 4.0 today. Can you test with the new cookbook and open a new ticket if the problem persists.
