### ISSUE TITLE
to fix syslog

### ISSUE THREAD

**Issue by sdarwin** [sous-chefs/haproxy#121]
After a fresh install on Debian/Ubuntu, you have to restart rsyslog as a one-time action:

service 'rsyslog' do
  action :restart
end

Otherwise logging still goes in /var/log/syslog and not /var/log/haproxy.log.  
So the cookbook should send a notify to restart the rsyslog service.

**Comment by rshade** [comment]
in v4.0.0, we will not be touching any resources outside of haproxy. In your wrapper feel free to restart it.
