### ISSUE TITLE
order of operations can leave a broken state

### ISSUE THREAD

**Issue by howdoicomputer** [sous-chefs/haproxy#138]
Because of how the cookbook handles the haproxy service, if a broken haproxy.cfg is pushed then a 'correct' haproxy configuration can't be subsequently pushed to fix the problem.

This is because the install recipe starts the haproxy service *before* the template resource executed. That being said, there doesn't seem to be a need to start haproxy before a configuration file is laid down?

Anyway, solved this locally by just enabling the service in my wrapper cookbook.

```
edit_resource!(:service, 'haproxy') do
  action [:enable]
end
```

**Comment by ChadScott** [comment]
+1

Just ran into this. A simple typo will bring down every balancer and require shenanigans to get it up and running again.

I've been destroying the instance in Test Kitchen and recreating it to remove the stale state but if it inadvertently got pushed to production, it'd be a real problem.

**Comment by rshade** [comment]
@ChadScott can you try with the latest version?
