### ISSUE TITLE
Not possible to create multi instance of haproxy

### ISSUE THREAD

**Issue by kfarhane28** [sous-chefs/haproxy#141]
The recipe install_<method> operate on the same name of init file, which is "/etc/init.d/haproxy"
We have a need to create several instances of haproxy, each with init file.
Example: an haproxy insatnce for service1, with /etc/init.d/haproxy_service1
A second instance of haproxy for service2, with /etc/init.d/haproxy_service2

Is it possible to allter this recipe, to include this need ?
thank you

**Comment by damacus** [comment]
This cookbook is not currently designed to support multiple instance of HAProxy on the same node. 

Right now we plan on squashing bugs getting testing up to speed, so the request won't be looked at for a while.

**Comment by damacus** [comment]
@kfarhane28 we've released the v4 version of this cookbook. Can you let us know if this now fixes  the issue?
