### ISSUE TITLE
Changes to default haproxy member attributes not sticking

### ISSUE THREAD

**Issue by jgrover** [sous-chefs/haproxy#143]
I'm running **haproxy 2.0.2** that I obtained through the **knife cookbook site haproxy install** command on my workstation running Chef v12.16.42.   I deployed haproxy to my Ubuntu 16.04 node successfully; however, my tweaks to the default['haproxy']['members'] attribute did not get carried over when it was added to the node.

Here is a snippet of my cookbooks/haproxy/attributes/default.rb file on my workstation:
```
default['haproxy']['incoming_port'] = 80
default['haproxy']['members'] = [{
'hostname' => 'webserver1', 
'ipaddress' => '192.168.1.136'
}, {
'hostname' => 'webserver2', 
'ipaddress' => '192.168.1.137'
}]
```

Here is a snippet of the resulting /etc/haproxy/haproxy.cfg on the load_balancer node:

```
frontend http
   maxconn 2000
   bind 0.0.0.0:80
   default_backend servers-http

backend servers-http
   mode http
```

As you can see, the member attributes were not added to the backend servers-http section :(  Am I doing something wrong?

Here is the process I went through:

- Tweaked the attributes/default.rb file to reflect my new members
- Added the cookbook to the chef server
- Set the node's run_list to be **recipe[haproxy::app_lb]**
- Ran **sudo chef-client** on the node. No errors reported.

When I manually add my webservers to the /etc/haproxy/haproxy.cfg file on the node, everything works perfectly, but of course, this is not optimal :(

Help!! :)

**Comment by shortdudey123** [comment]
`members` is used by the default recipe
while `pool_memebrs` is used by the `app_lb` recipe

**Comment by jgrover** [comment]
Thanks!  That did the trick.

I also found that when I created a new role named "webserver" and added my two webservers to it, the app_lb recipe automatically picks them up (through its included _discovery recipe). This is great.
