### ISSUE TITLE
Drop Chef Search for Cluster management

### ISSUE THREAD

**Issue by damacus** [sous-chefs/haproxy#148]
As this is not recommended behaviour for a cluster (we should be using something else like consul) do we want to remove the _discovery mechanism? 

Or make it just accept an array that some other tool can populate?

**Comment by rshade** [comment]
it looks to me to be already an array: https://github.com/sous-chefs/haproxy/blob/master/recipes/manual.rb#L84, if you run in daemon mode it could be a useful feature in an autoscaling environment.
