### ISSUE TITLE
thought on adding in sysctl setting in recipes/tuning.rb

### ISSUE THREAD

**Issue by rshade** [sous-chefs/haproxy#155]
what are the thoughts on updating the sysctl settings in recipes/tuning.rb
net.ipv4.tcp_tw_reuse = 1
net.ipv4.ip_local_port_range = 1024 65535
and possibly limits. Here are a couple of references: 
http://pastebin.com/8Hsv3n0u
https://wiki.mikejung.biz/Sysctl_tweaks

**Comment by damacus** [comment]
Closed by #164
