### ISSUE TITLE
Allow multiple ACL's inside haproxy_lb provider

### ISSUE THREAD

**Issue by FireDrunk** [sous-chefs/haproxy#159]
https://github.com/sous-chefs/haproxy/blob/master/providers/lb.rb#L13

This line makes it impossible to have an array of ACL's.
Is it possible to change the line to incorporate 'sub'-array's / hashes?

I would like to be able to define multiple 'acl' lines and multiple 'use_backend' lines to incorporate header switching.

**Comment by rshade** [comment]
does this look like it would fix your problem: #106

**Comment by rshade** [comment]
can you test against branch 106_MERGE
