### ISSUE TITLE
Using HAproxy cookbook as reverse proxy

### ISSUE THREAD

**Issue by ih16** [sous-chefs/haproxy#161]
Hi, 

I am using this cookbook with the manual recipe to create an HAcluster instance, but I'm running into an issue which presumably is a limitation with the community cookbook. 

To support an reverse proxy function I need to split every service into a seperate backend on which I can place ACL's.

Two things are unclear for me:

Does the manual recipe support acls? 
Does the cookbook supports multiple backends with the manual recipe?

Thanks in advance

**Comment by rshade** [comment]
@ih16 you're best bet may be to use the haproxy lwrp: https://github.com/sous-chefs/haproxy#haproxy

**Comment by ih16** [comment]
Thanks!
