### ISSUE TITLE
HAProxy search functionality and test/example

### ISSUE THREAD

**Issue by mengesb** [sous-chefs/haproxy#203]
### Cookbook version
4.0.2

### Chef-client version
12.19.36

### Platform Details
CentOS 6.x

### Scenario:
Testing issue

### Steps to Reproduce:
N/A

### Expected Result:
N/A

### Actual Result:
N/A

Looking to add tests for search functionality and perhaps also examples of code to provide the user more context around dynamic utilization of the haproxy providers.

```ruby
backend_array = search(:node, "roles:app AND chef_environment:#{environment}")
backend_array.each do |b|
  haproxy_backend b['id'] do
  end
end
```

**Comment by rshade** [comment]
I am going to try and do this test with the help of yall. Just wanted to include you guys on the assignee so you saw this. I think its a pretty cool example. feel free to remove yourself if uninterested

**Comment by rshade** [comment]
fixed here: https://github.com/sous-chefs/haproxy/blob/master/test/fixtures/cookbooks/test/recipes/config_backend_search.rb
