### ISSUE TITLE
Feature: support userlist

### ISSUE THREAD

**Issue by mengesb** [sous-chefs/haproxy#207]
### Cookbook version
4.0.2

### Chef-client version
12.19.36

### Platform Details
CentOS 6

### Scenario:
Create userlist blocks:
```
userlist stats-auth
    group admin    users admin
    user  admin    insecure-password AdMiN123
    group readonly users haproxy
    user  haproxy  insecure-password haproxy

backend stats_auth
    stats enable
    acl AUTH       http_auth(stats-auth)
    acl AUTH_ADMIN http_auth_group(stats-auth) admin
    stats http-request auth unless AUTH
    stats admin if AUTH_ADMIN
```

### Steps to Reproduce:
Feature request. The backend or listen providers can handle via `extra_options` the additional stats directives, or in the case of `haproxy_config_default` via the hash.

### Expected Result:
Create the above desired configuration without having to customize a template

Reference: https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#3.4

### Actual Result:
N/A

**Comment by rshade** [comment]
@mengesb you just want a userlist resource?

**Comment by mengesb** [comment]
That's correct. We might also want to investigate primitives for adding ACL to various segments as well, though again that can be handled by extra_options as well.

**Comment by rshade** [comment]
yep, I was considering an `acl` resource also

**Comment by damacus** [comment]
Or we can add a userlist section like ACL.
