### ISSUE TITLE
Update stats on frontend, listen, backend, defaults providers to be hash 

### ISSUE THREAD

**Issue by mengesb** [sous-chefs/haproxy#208]
### Cookbook version
4.0.2

### Chef-client version
12.19.36

### Platform Details
CentOS 6

### Scenario:
Documentation compliance with HAProxy documented features on the stats segment

### Steps to Reproduce:
N/A - Providers implement various pieces of stats at different levels, this is to bring them in-line with documentation

### Expected Result:
Documentation compliance configuration

### Actual Result:
stats is a hash only at the config_defaults provider. Various settings of stats can be performed at different levels per documentation:
https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#3.4

Instead of handling all the various settings levels of the stats directive, we should configure the stats directive as a hash and allow reasonable sane defaults. One default in the current version is within the stats hash setting `uri` to `/haproxy-stats` in config_defaults, then using `stats_uri` defaulted to `/` in listen. This is likely unintended and shouldn't be conflicting

Reference documentation mentioned above, various `stats` directives are available at different configuration levels - we should allow the user to fail and if we want to get fancy detect the stats blunder and redirect them to the correct documentation; or just to the head of the docs in general.

**Comment by rshade** [comment]
https://cbonte.github.io/haproxy-dconv/1.6/configuration.html#4.2-stats%20enable

**Comment by rshade** [comment]
@teknofire I heard you say you wanted this one so, I assigned it to you. Work your magic...
