### ISSUE TITLE
haproxy service not properly configured through AWS OpsWorks stacks

### ISSUE THREAD

**Issue by saintobr** [sous-chefs/haproxy#214]
### Cookbook version
4.1.0

### Chef-client version
chef-client 12.18.31
OpsWorks Stacks uses Chef Zero (logs show 12.13.37)

### Platform Details
The configuration is done using the latest Amazon AMI with OpsWorks Stacks

### Scenario:
I try to achieve a very basic installation of haproxy from sources using AWS OpsWorks Stacks.
Note that everything is fine when executed the recipe with Kitchen on centos 6.8 (I tried this because Amazon AMI seems to be derivated from centos 6).

### Steps to Reproduce:
Create an OpsWorks Stacks layer configured to run a very basic recipe with all default values performing the installation from sources, and launch an ec2 instance with the latest AMI.
There may be another simpler way.

### Expected Result:
The haproxy service should be up and running

### Actual Result:
The service cannot start because the exec path is invalid. 
The resulting init.d/haproxy file shows
`
config="/haproxy.cfg"
exec="/sbin/haproxy"
`

The variables @conf_dir and @prefix seems to be left blank

**Comment by rshade** [comment]
can you include your recipe?

**Comment by damacus** [comment]
Looks like it's broken wherever `::File.join` is used, which version of Ruby is on that machine?

**Comment by damacus** [comment]
Hi @saintobr we recommend you not use this with OpsWorks Stacks and try it with OpsWorks Automate instead as it is a much newer version of Chef, and much similar to the standard stack (as a result you'll likely not run into this issue. 

Another test you could do, would be to spin up an EC2 image in kitchen-ec2 and run the haproxy test suites against it. 
If you need help doing the latter please drop by the chef community slack and we'll talk you through debugging this more!

**Comment by saintobr** [comment]
Thanks a lot guys everything is fine now !
