### ISSUE TITLE
Cannot select version of HAProxy

### ISSUE THREAD

**Issue by paulius005** [sous-chefs/haproxy#220]
### Cookbook version
4.2.0

### Chef-client version
12.13

### Platform Details
Opsworks Amazon Linux 2017.03

### Scenario:
I am trying to run any version of HAProxy besides 1.5.2 which is what it seems to be defaulting to 
<img width="631" alt="screen shot 2017-05-08 at 10 36 41 pm" src="https://cloud.githubusercontent.com/assets/3084367/25836876/427da3e0-343f-11e7-8a07-99efec856a0e.png">
```
haproxy_install 'package' do
  source_version node[:haproxy][:source_version]
  source_url node[:haproxy][:source_url]
  source_checksum node[:haproxy][:source_checksum]
end
```

```
default[:haproxy][:source_version] = '1.7.5'
default[:haproxy][:source_url] = 'http://www.haproxy.org/download/1.7/src/haproxy-1.7.5.tar.gz'
default[:haproxy][:source_checksum] = 'b04d7db6383c662eb0a421a95af7becac6d9744a1abf0df6b0280c1e61416121'
```

I copied these values over from the `install.rb` file in the repo, but for some reason 1.5.2 keeps being installed. I also see no mention int he repo of `1.5` or `1.5.2` so I'm not sure why it's installing that version.

**Comment by shortdudey123** [comment]
looks like you are missing `install_type 'source'` on the resource

**Comment by shortdudey123** [comment]
oh, nvm, i see it
You are telling it to install package so it ignores your other options
`haproxy_install 'package'`

**Comment by paulius005** [comment]
```
haproxy_install 'source' do
  source_version node[:haproxy][:source_version]
  source_url node[:haproxy][:source_url]
  source_checksum node[:haproxy][:source_checksum]
end
```

doing this seems to install the correct version, now just working out some kinks for starting it up

Still not sure why it would install `1.5.2` when running `haproxy_install 'package'`

**Comment by shortdudey123** [comment]
`1.5.2` is probably the version thats available in the yum repo's available to the instance

**Comment by paulius005** [comment]
ah right.

this can be closed now.

Just a quick note for reference if anyone else runs into this issue. 

```
directory '/var/lib/haproxy' do
  owner 'root'
  group 'root'
  mode '0777'
  action :create
end
```

had to create this folder to get stats to work properly with 1.7.5

**Comment by rshade** [comment]
@paulius005 glad to hear. you can probably store the stats socket somewhere else also.
