### ISSUE TITLE
frontend with no default backend

### ISSUE THREAD

**Issue by paulius005** [sous-chefs/haproxy#225]
### Cookbook version
latest

### Chef-client version
12.x

### Platform Details
Latest amazon linux

### Scenario:
frontend with no default backend

in a case where ssl forwarding is needed, a `default_backend` should not be required no?

ie: 

```
frontend http-in
  bind *:80
  maxconn 50000
  redirect scheme https code 301 if !{ ssl_fc }
```

**Comment by rshade** [comment]
@paulius005 I think you are right there, can you submit either a working config, or a test to go with this so we can try it, and make sure haproxy starts?

**Comment by rshade** [comment]
@teknofire @damacus thoughts?

**Comment by damacus** [comment]
If it starts and passes tests. Sure! 

We'd need another config for this rather than bastardising a current config.
