### ISSUE TITLE
Update tests to have anchors and whitespace matchers for proper formatting

### ISSUE THREAD

**Issue by rshade** [sous-chefs/haproxy#228]
### Cookbook version
Latest

### Chef-client version
NA

### Platform Details
NA

### Scenario:
The tests currently just match for the straight string. They should also match for it's left/right position in the file, to make sure its in the proper format. 

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by teknofire** [comment]
The example for what needs to be fixed are the matches like `match(/backend servers/)` that will match both the `backend` config and the `default_backend` setting in the `frontends`.

**Comment by damacus** [comment]
Still needed @teknofire ?

**Comment by rshade** [comment]
yep, we need to have it at the proper location.

**Comment by damacus** [comment]
@rshade fancy submitting a PR?

**Comment by JohnRoesler** [comment]
I could take this one on
