### ISSUE TITLE
haproxy_install breaks on OEL6

### ISSUE THREAD

**Issue by julian7** [sous-chefs/haproxy#230]
### Cookbook version
4.3.0

### Chef-client version
13.0.118

### Platform Details
Oracle Linux Server release 6.6

### Scenario:
haproxy_install creates an incompatible init script, which fails to load /lib/lsb/init-functions

### Steps to Reproduce:
no strings attached: create a default haproxy_install resource on a OEL6 system.

### Expected Result:
A redhat-compatible init script is installed

### Actual Result:
A debian-compatible init script gets installed

---

I found haproxy_install resource creates a poise_service with sysvinit provider, with no option for skipping it. It also provides a cookbook and template name as string literal, with no options to configure. Then, platforms amazon, centos and redhat are handled as special case, making debian as a fallback option.

I know of oracle and science linux (which are in the supported distributions list), which get the fallback template.

**Comment by rshade** [comment]
Can you do a pull request? and possibly add a test?

**Comment by julian7** [comment]
For now I've replicated the functionality into my configuration cookbook, I can prepare something early next week. Most likely redhat/centos init script has to be copied under templates/oracle/. Alternatively, we can have a separate flow of actions for debian and rhel platform families, just like how systemd is handled.

@rshade, what do you think?

**Comment by rshade** [comment]
I think that should probably be all it needs, and added to the list on the case, then a test in .kitchen.dokken.yml and .travis.yml
