### ISSUE TITLE
The `config_global.rb` should allow `log` property to be an `Array` type

### ISSUE THREAD

**Issue by bharathcp** [sous-chefs/haproxy#252]
### Cookbook version
4.6.0

### Chef-client version
any

### Platform Details
any

### Scenario:
I should be able to define more than one log entry in the global config like:
```
log /dev/log local0
log /dev/log local1 notice
```
I cannot do that since the `log` property is a `String` type and not an `Array` type.

### Steps to Reproduce:
none

### Expected Result:
none
### Actual Result:
none

**Comment by damacus** [comment]
Closed by #259
