### ISSUE TITLE
Documentation expansion request

### ISSUE THREAD

**Issue by et304383** [sous-chefs/haproxy#262]
I think the community would benefit from documentation on what each of the resources does.

There are some examples in the readme, but no explanation as to what each is doing, what properties exist, what actions are supported, etc.

**Comment by rshade** [comment]
@et304383 we are moving towards examples in the test directory would that work for you?

**Comment by et304383** [comment]
It's a start, but I do appreciate when a README fully documents each resource including a description for each attribute.

But definitely, this is an improvement!

**Comment by damacus** [comment]
Hey @et304383

What are you looking at getting out of a fully documented resource?

- 1:1 mapping of resource to actions, inputs etc to documentation
- common use cases general use etc.
, - something else? (if so we'd love to hear how we can improve here) 

I'm in favour of something like the second as a 1:1 mapping would require auto generation, and can get out of sync quite easily if not done that way.
This can also lead to there being more documentation than code. Whilst that isn't something inheritantly bad, we do have an amount of bandwidth to cope with building out these cookbooks. And this would be a great PR opportunity if you or anyone else is up for it (even just an initial prod).

**Comment by et304383** [comment]
As I said, the examples help a lot.  I understand concerns around time so I get if having full documentation of every attribute of every resource isn't in scope.

The examples have definitely solved my immediate issues with not knowing what to do, so you can consider this issue solved.

**Comment by damacus** [comment]
Brilliant, glad they helped 👍
