### ISSUE TITLE
No good way to bind one frontend to multiple ports

### ISSUE THREAD

**Issue by alexs77** [sous-chefs/haproxy#267]
### Cookbook version
5.0.0.

### Chef-client version
12.21.4, chef local mode (zero)

### Platform Details
Ubuntu 16.04

### Scenario:
Need to bind one frontend to more than one port on the same IP.

### Steps to Reproduce:

```ruby
bind = {
  "192.168.0.1": "80",
  "192.168.0.1": "8080",
  "192.168.0.1": "443 ssl crt /etc/haproxy/ssl/foo.pem"
}

haproxy_frontend "testing" do
    action :create
    bind bind
end
```

If the value of the `bind` property is a Hash, the key is supposed to be the IP and the value is the port (with possibly additional options, like `ssl …` in my case). But one IP (ie. one key) cannot be used more than once.

If haproxy should answer requests on all IPs/devices, one can go hacky like so:

```ruby
bind = {
  "*": "80",
  "0.0.0.0": "443 ssl crt /etc/haproxy/ssl/foo.pem"
}
```

But this doesn't work for more than two binds.

### Expected Result:

Maybe the value of the `bind` property should/could be an array as well. An array of simple strings:

```ruby
bind = [
  "192.168.0.1:80",
  "192.168.0.1:8080",
  "192.168.0.1:443 ssl crt /etc/haproxy/ssl/foo.pem"
]
```

And then the `haproxy_frontend` resource should create a `frontend …` configuration in `haproxy.cfg` with multiple `bind …` lines.

### Actual Result:

1)

```ruby
bind = {
  "192.168.0.1": "80",
  "192.168.0.1": "8080",
  "192.168.0.1": "443 ssl crt /etc/haproxy/ssl/foo.pem"
}
```

Result: Only one `bind` line is written (with port 443, as it's the last entry).

2)

```ruby
bind = [
  "192.168.0.1:80",
  "192.168.0.1:8080",
  "192.168.0.1:443 ssl crt /etc/haproxy/ssl/foo.pem"
]
```

Chef generates an error, as the value of the property needs to be a string or a hash.

**Comment by rshade** [comment]
@alexs77 would you be willing to put in a pull request?

**Comment by damacus** [comment]
This is getting to the point of, everything needing to be a hash. I generally dislike having haproxy listening on multiple ports for the same backend, but know it's needed in some circumstances.

If you fancy creating a PR on this one, that'd be great.

**Comment by damacus** [comment]
I think the solution in #268 should work
