### ISSUE TITLE
extra_options should be an Array

### ISSUE THREAD

**Issue by alexs77** [sous-chefs/haproxy#268]
### Cookbook version
5.0.0.

### Chef-client version
12.21.4, chef local mode (zero)

### Platform Details
Ubuntu 16.04

### Scenario:

Need to have multiple "redirect" or "http-response" statements in `frontend`.

This is probably related to issue #267

Need to bind one frontend to more than one port on the same IP.

### Steps to Reproduce:

The value of the `extra_options` property at the moments needs to be a Hash. The following thus doesn't work.

```ruby
extra_options = {
  "redirect": "scheme https cod 301 if !{ ssl_fc }",
  "redirect": "… something else …"
}

haproxy_frontend "testing" do
    action :create
    extra_options extra_options
end
```

If the value of the `extra_options` property is a Hash, it's not possible to use a key more than once.

### Expected Result:

Maybe the value of the `extra_options` property should/could be an array as well. An array of simple strings:

```ruby
extra_options = [
  "redirect scheme https cod 301 if !{ ssl_fc }",
  "redirect … something else …"
]
```

And then the `extra_options` resource should create a `frontend …` configuration in `haproxy.cfg` with multiple lines, containing whatever was in the array.

### Actual Result:

```ruby
extra_options = [
  "redirect scheme https cod 301 if !{ ssl_fc }",
  "redirect … something else …"
]
```

Chef generates an error, as the value of the property needs to be a Hash.

**Comment by eheydrick** [comment]
This is definitely needed. I have a config that requires setting multiple `rspirep` and `http-request` options and a hash won't work. The pre 4.x version took a [hash or an array](https://github.com/sous-chefs/haproxy/blob/v3.0.4/resources/lb.rb#L18). If it supported both we could remain backwards compatible.

**Comment by eheydrick** [comment]
I need to do a little more testing but making the property take a hash or an array seems to work without having to modify anything else. If you want something that works now there is a workaround. You can supply an empty named hash with a value that's an array of options. Like this...

```
haproxy_frontend 'web' do
  mode 'http'
  extra_options(
    "":
    [
      "redirect scheme https code 301 if !{ ssl_fc }",
      "redirect … something else …"
    ]
  )
end
```

**Comment by damacus** [comment]
Yeah so we moved away from just supporting a Hash or Array because it's super hard to test and maintain. 

What @eheydrick has suggested is a really nice workaround. Would one of you mind adding this to the readme?

**Comment by nathwill** [comment]
just fyi, you can use [Hash#compare_by_identity](https://ruby-doc.org/core-2.4.2/Hash.html#method-i-compare_by_identity) to get past the hash key uniqueness limitation

**Comment by damacus** [comment]
I'm going to close this one down now. I believe it's fixed as much as we're likely to do now.

**Comment by fxrsliberty** [comment]
does not work!

 98  extra_options(
 99    'balance' => 'roundrobin',
100     'cookie' => 'SERVID insert indirect nocache',
101     'reqirep' => '^([^\ ]*)\ /config/?([^\ ]*)\ (.*)$    \1\ /inap-customer-portal-service/\2\ \3',
102     "": [
103     "rspirep  ^([^\ ]*)\ /inap-customer-portal-service/?([^\ ]*)\ (.*)$    \1\ /config/\2\ \3",
104     "rspirep  ^(Location:)\ https://([^/]*)/(.*)$       \1\ https://\2/inap-customer-portal-service/\3",
105     "rspirep  ^(Set-Cookie:.*\ path=)([^\ ]+)(.*)$      \1/config\2\3"
106     ]
107   )
108 end

**Comment by gerard-leijdekkers** [comment]
>   extra_options(
>     "":
>     [
>       "redirect scheme https code 301 if !{ ssl_fc }",
>       "redirect … something else …"
>     ]

I am using this for http-request statements. It will result in an extra space before the option and that makes HAProxy (1.6.3) behave weird. Two spaces however are fine, so the hash-key should be a space in stead of an empty string.
