### ISSUE TITLE
resource/frontend.rb named incorrectly and preventing converge

### ISSUE THREAD

**Issue by JJClements** [sous-chefs/haproxy#269]
### Cookbook version
5.0.0 (latest)

### Chef-client version
12.12.15

### Platform Details
Ubuntu 14.04

### Scenario:
I cannot converge this cookbook, as two resources called from within the **recipes/default.rb** recipe do not match actual the name of the resource(s) in the resource directory.

### Steps to Reproduce:
Create a wrapper cookbook with an empty attributes.rb file, and in the default.rb recipe for the wrapper cookbook simply add an include to the default recipe of this haproxy cookbook (include_recipe 'haproxy')

### Expected Result:
The cookbook should converge cleanly and HAProxy should be installed

### Actual Result:
Converge fails with:
`NoMethodError`
`-------------`
`No resource or method named 'haproxy_config_frontend' for 'ChefCompat::Recipe "default"'`

### Notes:
This appears to be the case for both the **resources/frontend.rb** and the **resources/backend.rb** resource files.
Renaming **frontend.rb** to **config_frontend.rb** and **backend.rb** to **config_backend.rb** allows for a successful converge.

**Comment by c240amg** [comment]
Having the same issue.

**Comment by rshade** [comment]
```
# This recipe is for an example only,
# it is not supported in a runlist.
# It will only create a blank useless configuration```
The default.rb recipe is not intended to be functional in any way.

**Comment by josephholsten** [comment]
@JJClements good find! Do you have time to write up a PR for this? I don't think we want to start supporting recipes again, but it would be nice for them not to be misleading.

**Comment by josephholsten** [comment]
Also, your desired "Expected Result" is not a thing this cookbook will ever do from the default recipe. How do you think we could document that to help avoid confusion in the future?

**Comment by teknofire** [comment]
IMO the recipe should be completely removed we should direct users to look at the recipes in the test cookbook in the `README.md` since those will be tested and alwayss up to date.

If you want, the `default` recipe be updated to be only a comment redirecting the user to look at the test recipes.

**Comment by thommay** [comment]
I think it's probably better to just not have a recipe rather than have a blank one, so it's clear very quickly that what you're trying to do is not supported.

**Comment by JJClements** [comment]
I agree the recipe should be completely removed in that case. But, the documentation should be updated to better reflect other scenarios, and preferebly include an example for every resource.

I still don't know whether it's better to rename the resource files, or just change the documentation (readme.md) to rectify this. I don't mind creating a PR either way...

**Comment by damacus** [comment]
In that case we should probably point people to the tests directory (which is pretty common now) for documentation. 

Any chance you can make a PR for this clarification please?
