### ISSUE TITLE
Resource configs_default.rb property cannot be null

### ISSUE THREAD

**Issue by JJClements** [sous-chefs/haproxy#271]
### Cookbook version
5.0.0 (latest)

### Chef-client version
12.12.15

### Platform Details
Ubuntu 14.04

### Scenario:
configs_default.rb sets a default stats uri as per: https://github.com/sous-chefs/haproxy/blob/9c050820eafb6db1064364a79b40447db8c7ce8f/resources/config_defaults.rb#L7
It would be good if this wasn't set by default, as I suspect many users typically don't want to expose stats externally for **every** frontend? I typically create an individual listener (that is only available on a port internally) that we can access for stats. Setting the stats uri in configs_default.rb enables it for all frontends (which we have exposed to the internet).

### Steps to Reproduce:
Use the configs_default.rb resource, stats uri is then automatically populated if not defined in haproxy.cfg, overriding it and setting it to null causes the cookbook converge to fail.

### Desired Result:
If the stats uri is not defined in configs_default.rb, it doesn't get set in the haproxy.cfg file by default. If we want to expose stats we can set a uri in configs_default.rb ourselves OR create a independent listener for it. I guess similar to how it's been written for the listen.rb resource: https://github.com/sous-chefs/haproxy/blob/9c050820eafb6db1064364a79b40447db8c7ce8f/resources/listen.rb#L5

### Actual Result:
Using the configs_default.rb creates a default stats uri of **/haproxy-status**. Overiding the property to null on the resource causes a cookbook converge to fail. All frontends will then expose **/haproxy-status**.

**Comment by JJClements** [comment]
Actually, it seems the stats property can be 'disabled' from config_defaults.rb using an empty hash:
`stats {}`

It might be worth making it blank in config_defaults.rb by default though? Or at least documenting it this the readme?

**Comment by rshade** [comment]
@JJClements thanks man, want to take a crack at a pull request to the readme. I can merge that today?

**Comment by akmalabbasov** [comment]
This is solved by https://github.com/sous-chefs/haproxy/pull/275 @rshade

**Comment by psyreactor** [comment]
Hi,
To clean the value of stats or another value that has default value, you have to pass an empty hash.

example:

haproxy_config_defaults 'defaults' do
  'http' mode
  balance 'source'
  stats **Hash.new**
  timeout connect: '5000ms',
          client: '5000ms',
          server: '5000ms'
end

Regards!!

**Comment by damacus** [comment]
Fixed via #279
