### ISSUE TITLE
Can't send haproxy service notifications

### ISSUE THREAD

**Issue by eheydrick** [sous-chefs/haproxy#274]
### Cookbook version
5.0.0

### Chef-client version
12.20

### Platform Details
Ubuntu 16.04

### Scenario:
I want to send haproxy a reload notification when other files are updated. For example when an SSL cert is updated.

### Steps to Reproduce:

In haproxy cookbook 2.x I could do this and it would reload haproxy when the cert file was updated. 

```
file '/etc/haproxy/ssl/haproxy.pem' do
  owner 'root'
  group 'root'
  mode '0400'
  sensitive true
  content "my-cert"
  notifies :reload, 'service[haproxy]'
end
```

As a workaround I can add 
```
service 'poise_haproxy' do
  action :nothing
end
```
and do `notifies :reload, 'poise_service[haproxy]'`

but it would be nice if resource notifications worked out of the box.

### Expected Result:
I expect there to be a way to send haproxy reload notifications.

### Actual Result:
```
[2017-10-12T23:20:02+00:00] ERROR: resource file[/etc/haproxy/ssl/haproxy.pem] is configured to   
 notify resource service[haproxy] with action reload, but service[haproxy] cannot be found in the  
 resource collection. file[/etc/haproxy/ssl/haproxy.pem] is defined in  
 /tmp/kitchen/cache/cookbooks/my-thing/recipes/proxy.rb:27:in `from_file'
```

**Comment by damacus** [comment]
Try this instead 
`notifies :reload, 'poise_service[haproxy]', :immediately`

eventually we'll strip out the poise service stuff and make it more obvious. But poise has some nice template handling for systemd right now.

**Comment by eheydrick** [comment]
I get the same `poise_service[haproxy] cannot be found in the resource collection` error when trying that. Doing the `action :nothing` workaround is the only thing I've found that works. I suspect the problem comes from the service being defined in the custom resource.

**Comment by damacus** [comment]
I remember having this problem when I first setup the service. 

```
with_run_context :root do
file '/etc/haproxy/ssl/haproxy.pem' do
  owner 'root'
  group 'root'
  mode '0400'
  sensitive true
  content "my-cert"
  notifies :reload, 'service[haproxy]'
end
end
```

Because we had to throw everything in the shared root context so we could accumulate the resources. 

FYI: Here's where we setup the service https://github.com/sous-chefs/haproxy/blob/master/resources/install.rb#L103

**Comment by rshade** [comment]
@eheydrick does that help?

**Comment by eheydrick** [comment]
The only thing that I was able to get working was adding a `:nothing` resource for `service[poise_haproxy]` and notifying that per the repro steps in the issue. Would be nice if notifications worked out of the box but at least there's a workaround.

**Comment by rshade** [comment]
did you try the root_context item above?

**Comment by eheydrick** [comment]
Yes, didn't work. I get: 

```
 2017-12-06T20:03:28+00:00] ERROR: resource file[/etc/haproxy/ssl/haproxy.pem] is configured to
 notify resource service[haproxy] with action reload, but service[haproxy] cannot be found in the
 resource collection. file[/etc/haproxy/ssl/haproxy.pem] is defined in
 /tmp/kitchen/cache/cookbooks/my-thing/recipes/proxy.rb:31:in `block in from_file'
```

**Comment by LMolr** [comment]
It looks like the `install` resource exposes actions to handle the haproxy service:
https://github.com/sous-chefs/haproxy/blob/master/resources/install.rb#L168-L198

Not sure if it suits the OP's needs..

**Comment by damacus** [comment]
@eheydrick are you still having  this issue?

**Comment by eheydrick** [comment]
Last I checked I was. Still using the dummy `service` as a workaround so I'm not totally blocked.

**Comment by mynamewastaken** [comment]
I was having the same issue as OP, but https://github.com/sous-chefs/haproxy/issues/274#issuecomment-369199041 worked for me. For anyone else who sat there scratching their head for a few minutes trying to figure out how to call it: `notifies :reload, 'haproxy_install[package]', :delayed` worked for me.

**Comment by damacus** [comment]
I wonder if we could/should split out the Haproxy_service into its own resource?

Then call everything from there?

**Comment by jenrzzz** [comment]
This doesn't seem to be working for me on 6.2.0. The notify works and the reload/restart action seems to be executed, but it looks like the service installation is deferred until the very end of the run, so the systemd service doesn't actually exist at the time the restart is executed.

**Comment by Stromweld** [comment]
I had similar issue but was able to work around it by adding subscribes option in the service haproxy resource.
```
haproxy_service 'haproxy' do
  source_version node['haproxy']['version']
  subscribes :reload, 'template[/etc/haproxy/haproxy.cfg]', :immediately
end
```

**Comment by Stromweld** [comment]
@damacus @rshade looking at the code further to restart or reload haproxy the resource has those actions so it would be called via `notifies :reload, 'haproxy_service[haproxy]', :delayed` would it not?

**Comment by damacus** [comment]
That does seem reasonable, can you test this for us please @Stromweld ?

**Comment by damacus** [comment]
Adding the documentation label as we need to document this for future users.

**Comment by Stromweld** [comment]
yes I can, but it'll take me a few days, I have to finish a big project for work at the moment.

**Comment by f9n** [comment]
Same here!
Cookbook Version: 6.2.5
Chef-Client Version: 14.5.33
Platform: bento/centos-7     (virtualbox, 201807.12.0)

```ruby
# My haproxy wrapper: yildiz-haproxy
haproxy_install 'package'

haproxy_config_global ''

haproxy_config_defaults ''

haproxy_frontend 'http-in' do
  default_backend 'servers'
end

web_server_1 = 'apache-1 192.168.10.41:80'
web_server_2 = 'apache-2 192.168.10.42:80'

haproxy_backend 'servers' do
  server [web_server_1, web_server_2]
  notifies :reload, 'haproxy_service[haproxy]', :immediately
end

haproxy_service 'haproxy'
```
```bash
$ sudo chef-client
[vagrant@load-balancer ~]$ sudo chef-client
Starting Chef Client, version 14.5.33
resolving cookbooks for run list: ["yildiz-haproxy"]
Synchronizing Cookbooks:
  - haproxy (6.2.5)
  - build-essential (8.2.1)
  - seven_zip (3.0.0)
  - mingw (2.1.0)
  - poise-service (1.5.2)
  - poise (2.8.2)
  - windows (5.1.3)
  - yildiz-haproxy (0.2.5)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 6 resources
Recipe: yildiz-haproxy::default
  * haproxy_install[package] action create
    * yum_package[haproxy] action install (up to date)
     (up to date)
  * poise_service_user[haproxy] action create
    * group[haproxy] action create (up to date)
    * linux_user[haproxy] action create (up to date)
     (up to date)
  * directory[/etc/haproxy] action create (up to date)
  * template[/etc/haproxy/haproxy.cfg] action nothing (skipped due to action :nothing)
  * haproxy_config_global[] action create (up to date)
  * haproxy_config_defaults[] action create (up to date)
  * haproxy_frontend[http-in] action create (up to date)
  * haproxy_backend[servers] action create (up to date)
  * haproxy_service[haproxy] action create (up to date)
  * cookbook_file[/etc/default/haproxy] action create (up to date)
  * poise_service[haproxy] action nothing (skipped due to action :nothing)
  * template[/etc/haproxy/haproxy.cfg] action nothing (skipped due to action :nothing)
  * template[/etc/haproxy/haproxy.cfg] action create
    ------------------------ Green = begin
    - update content in file /etc/haproxy/haproxy.cfg from f8b9ba to 755b5a
    - suppressed sensitive resource
    - restore selinux security context
    ------------------------- Green = end
  * poise_service[haproxy] action enable
    * execute[systemctl daemon-reload] action nothing (skipped due to action :nothing)
    * template[/etc/systemd/system/haproxy.service] action create (up to date)
    * service[haproxy] action enable (up to date)
    * service[haproxy] action start (up to date)
     (up to date)

Running handlers:
Running handlers complete
Chef Client finished, 1/21 resources updated in 09 seconds
```

When I change the `server` property in `haproxy_backend` resource, it doesn't reload the haproxy. Even if I use `:delayed` action, it doesn't work.

This works for me => https://github.com/sous-chefs/haproxy/issues/274#issuecomment-423570444

```bash
  .............................
  * poise_service[haproxy] action nothing (skipped due to action :nothing)
  * template[/etc/haproxy/haproxy.cfg] action nothing (skipped due to action :nothing)
  * template[/etc/haproxy/haproxy.cfg] action create
    - update content in file /etc/haproxy/haproxy.cfg from f8b9ba to e03b74
    - suppressed sensitive resource
    - restore selinux security context
  * haproxy_service[haproxy] action reload
    * poise_service[haproxy] action reload
      * service[haproxy] action reload
        - reload service service[haproxy]
    
     (up to date)
  * poise_service[haproxy] action enable
    * execute[systemctl daemon-reload] action nothing (skipped due to action :nothing)
    * template[/etc/systemd/system/haproxy.service] action create (up to date)
    * service[haproxy] action enable (up to date)
    * service[haproxy] action start (up to date)
     (up to date)

Running handlers:
Running handlers complete
Chef Client finished, 3/24 resources updated in 09 seconds
```

**Comment by JohnRoesler** [comment]
Checking in on this, I'm able to trigger reload with the subscribe, 

```
haproxy_service 'haproxy' do
  subscribes :reload, "template[#{node['haproxy-wrapper']['config']['path']}/haproxy.cfg]", :delayed
end
```

@f9n I see you don't have any service definition. Does it work adding the subscribe option to the config or other file you want to watch? Subscribing in the service vs. notifying from the backend update?

**Comment by damacus** [comment]
@johnroesler could you throw some docs together for service notifications please?

Once that's done I think we can call this done and closed.

That said if anyone else wants to jump in and document any of this cookbook better please jump in!
