### ISSUE TITLE
Wrapper cookbook?

### ISSUE THREAD

**Issue by mynamewastaken** [sous-chefs/haproxy#286]
### Cookbook version
5.0.3

### Chef-client version
12.15.19 (probably not relevant, though will be upgrading asap)

### Platform Details
Centos 7.4

### Scenario:
Because of how we're going to be organizing things I will have multiple haproxy nodes with slightly different configurations. I'm creating a generic wrapper cookbook (haproxy_wrap) that will do the basic setup we need (log rotation, selinux config, etc) and on top of that would be multiple role cookbooks (haproxy_team1, haproxy_team2, etc). I would like to be able to make a large configuration hash with sane defaults and pass that into the cookbook. Something like this:
```
config = {
  'global_config': {
    'user': 'haproxy',
  },
  'defaults_config': {
    'log': 'some.syslog.server:514',
  },
}
```
Is it possible to pass parts of my config to the various haproxy resources this cookbook provides?  Something like: 
```
haproxy_config_global '' do
  args config['global_config']
end
```

If that doesn't work, is my only other option to hardcode each of the currently listed properties (e.g.: `:log`, `:haproxy_user`, `:haproxy_group`) inside my wrapper cookbook, loop through and only set them if they exist? 

```
haproxy_config_global '' do
  user config['global']['user'] if config['global'].key?('user')
  group config['global']['group'] if config['global'].key?('group')
end
```

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by damacus** [comment]
HI @mynamewastaken I'm not quite sure what you're asking for here. 

But creating multiple wrapper cookbooks for haproxy would definitely work. 

You could start using node attributes when using those cookbooks. 

```ruby
default_wrapper/recipes/default.rb

haproxy_config_global '' do
  log node['my_org']['log_file']
  log_tag node['my_org']['log_tag']
end
```
```ruby
default_wrapper/attributes/default.rb

node.default['my_org']['log_file'] = '/var/log/default_log_file'
node.default['my_org']['log_tag'] = ''
```

Now override those attributes for team 1.
```ruby
team_1_wrapper/recipes/default.rb
node.override['my_org']['log_file'] = '/var/log/super_awesome_app'
node.override['my_org']['log_tag'] = 'team_1'
include_recipe 'default_wrapper/recipes/default.rb'

**Comment by mynamewastaken** [comment]
@damacus thanks for the quick reply. Looks like I'm going to end up going the attribute route - thanks!
