### ISSUE TITLE
Binary paths are not configurable in systemd unit file

### ISSUE THREAD

**Issue by UncleIS** [sous-chefs/haproxy#288]
Hello, colleagues.

It seems to be impossible to configure paths to haproxy binary in systemd unit file as showed below:

https://github.com/sous-chefs/haproxy/blob/8b66e60704562bf2f1deb95fa8384e8a26d90cf7/templates/default/haproxy.service.erb#L7

At the same time, the prefix can be specified when building haproxy from sources, which might cause confusion:

https://github.com/sous-chefs/haproxy/blob/8b66e60704562bf2f1deb95fa8384e8a26d90cf7/resources/install.rb#L5

**Expected result**
Systemd unit file would be generated considering possible changes in the build prefix inroduced by users in wrapper cookbooks.

**Observed result**
Paths to binaries specified in the systemd unit file are not configurable by automation.

**Environment**
RHEL 7.4
Chef 13.8.5

**Comment by damacus** [comment]
Hi @UncleIS! 

Thanks for taking the time to submit an issue. 

We would happily accept a pull request to resolve this issue. If you need help or guidance on submitting, please don't hesitate to ask! 

Thanks,
Sous-Chefs
