### ISSUE TITLE
The haproxy service is not reloaded but restarted

### ISSUE THREAD

**Issue by ddegoede** [sous-chefs/haproxy#290]
### Cookbook version
5.0.3

The changes made in #256 to reload the service are reverted back to restart, is this on purpose, or a unwanted side effect of merging #259?

See: https://github.com/sous-chefs/haproxy/blob/c3c0a398c0fae39f8d751e74c21c8a1372df7eab/resources/install.rb#L123

**Comment by damacus** [comment]
Hi there! 

Thanks for taking the time to submit an issue. 

We would happily accept a pull request to resolve this issue. If you need help or guidance on submitting, please don't hesitate to ask! 

If you need help, or just wish to talk through issue please [join the Chef Community Slack](http://community-slack.chef.io/) and look for the #sous-chefs channel. 

Thanks,
Sous-Chefs

**Comment by rshade** [comment]
Please checkout 6.1.0 and the new service resource. Also as of 1.8.5 of haproxy systemd reloads are better.
