### ISSUE TITLE
haproxy 1.8 issues in ubuntu 16.04

### ISSUE THREAD

**Issue by ostsjoe** [sous-chefs/haproxy#294]
### Cookbook version
5.0.4

### Chef-client version
12.19.36

### Platform Details
Ubuntu 16.04

### Scenario:
Building haproxy from source fails when haproxy 1.8.4 is used

### Steps to Reproduce:
Using haproxy_install in our wrapper cookbook, and setting version, url, and checksum parameters properly to 1.8.4

### Expected Result:
Haproxy is installed

### Actual Result:
==> haproxy:       Please run 'make' before 'make install'.
==> haproxy:
==> haproxy: Makefile:941: recipe for target 'install-bin' failed
==> haproxy:       STDERR: make: *** [install-bin] Error 1
==> haproxy:
==> haproxy: ---- End output of "bash"  "/tmp/chef-script20180403-11888-18dzh33" ----
==> haproxy:

This failure is due to the haproxy-systemd-wrapper missing in the 1.8 branch of haproxy. No current pull request as I'm still working out what all needs to change for 1.8 to work. As a side note, the changelog for this cookbook indicates 1.8.4 should be the default, it is not. 1.7.8 is still set in the install.rb resource through the 6.0.0 version.

**Comment by daveallen** [comment]
I have it working on a fork.  For 1.8 there is a new way it works with systemd.  There is a USE_SYSTEMD=1 compiler option.  This with the added command line option -Ws allows a better way to do reloads and communicates completion to systemd.  
Here is what I did.  
https://github.com/daveallen/haproxy/blob/master/resources/install.rb

**Comment by damacus** [comment]
FYI we're no longer supporting chef 12 as of v6 of the cookbook,  as its now eol

**Comment by daveallen** [comment]
Yep, wrapper gone.

**Comment by ostsjoe** [comment]
Tested @daveallen's branch and its working perfectly for me (haven't back tested it with 1.7 though) Thanks!

**Comment by daveallen** [comment]
I have. But please make sure. I like safe.

**Comment by damacus** [comment]
Fixed by #287 

Is this is incorrect please reopen!
