### ISSUE TITLE
How to achieve no downtime reloading scheme with haproxy 1.8

### ISSUE THREAD

**Issue by paulius005** [sous-chefs/haproxy#296]
### Cookbook version
6.10

### Chef-client version
13

### Platform Details
Ubuntu 16.04

### Scenario:
I am trying to leverage the new no downtime reloading scheme with haproxy 1.8 as demonstrated here: https://fabianlee.org/2017/10/16/haproxy-zero-downtime-reloads-with-haproxy-1-8-on-ubuntu-16-04-with-systemd/

What is needed to to be done with this cookbook to accomplish this?

I will gladly contribute to the repo or the README once I know which direction to head in!

**Comment by damacus** [comment]
Yes, that sounds good. If you want to sketch out what that would look like with 1.8, that'd be great.

**Comment by JohnRoesler** [comment]
FWIW, we are using the cookbook as is, no custom scripts, with haproxy version `1.8.13` and ran several load tests 10K TPS to a single server (8 core cpu, 16gb ram) and reloaded the haproxy configuration once per second and saw zero errors on http requests being proxied through.

**Comment by damacus** [comment]
That's awesome.

Maybe the feedback should just be, this behaviour is included, and verified on versions later than 1.8.13.


Closing as fixed. 
Thanks for everyone's feedback on this issue!
