### ISSUE TITLE
There is no way to add servers to a listen section.

### ISSUE THREAD

**Issue by daveallen** [sous-chefs/haproxy#298]
### Cookbook version
6.0.0

### Chef-client version
14.0.202

### Platform Details
Ubuntu 16.04, Vagrant, Test Kitchen

### Scenario:
Set up a listen section with servers.

### Steps to Reproduce:
Add a server option to haproxy_listen resource.

### Expected Result:
Servers added to the listen section

### Actual Result:
NoMethodError
         -------------
         undefined method `server' for Custom resource haproxy_listen from cookbook haproxy

**Comment by Stromweld** [comment]
servers property was added with PR #309
