### ISSUE TITLE
LInk to the test examples is bad: "The page you were looking for does not exist."

### ISSUE THREAD

**Issue by gforghetti** [sous-chefs/haproxy#301]
Haproxy 6.2.0
https://supermarket.chef.io/cookbooks/haproxy/versions/6.2.0

**Please check for working examples in test** is bad.

https://supermarket.chef.io/cookbooks/test/fixtures/cookbooks/test/
The page you were looking for does not exist.

### Cookbook version
6.20

### Chef-client version
N/A

### Platform Details
N/A

### Scenario:
Haproxy 6.2.0
https://supermarket.chef.io/cookbooks/haproxy/versions/6.2.0

**Please check for working examples in test** is bad.

https://supermarket.chef.io/cookbooks/test/fixtures/cookbooks/test/
The page you were looking for does not exist.

### Steps to Reproduce:
N/A

### Expected Result:
Working link

### Actual Result:
N/A

**Comment by mburns** [comment]
FWIW, the link in the README is a relative path.

Clicking it from the Supermarket page doesn't work, but clicking it [from Github](https://github.com/sous-chefs/haproxy/blob/master/README.md#examples) does.

**Comment by damacus** [comment]
Closing as resolved. 

Please reopen with a suggested fix.
