### ISSUE TITLE
on ubuntu 14, should we create an upstart-compatible service

### ISSUE THREAD

**Issue by caarlos0** [sous-chefs/haproxy#304]
Sorry for not answering the questions asked, but this is not a bug report.

If we created a `/etc/init/haproxy.conf`, we could for example add the `respawn` instruction to auto-restart haproxy if it crashes for some reason...

Would be a nice thing to have - alongside with the same thing for systemd and etc...

**Comment by damacus** [comment]
I'd be interested in someone picking this up with better haproxy experience than I. 

If anyone could weigh in, on possible solutions have at it.

**Comment by damacus** [comment]
As ubuntu 14.04 is going EOL soon, unless someone wants to implement this the cookbook isn't going to support this going forward as we'd be stripping out the feature pretty soon.
