### ISSUE TITLE
Other haproxy rules that need to be placed appropriately

### ISSUE THREAD

**Issue by JohnRoesler** [sous-chefs/haproxy#319]
Similar to #313 there are other rules that need to be placed properly.

I'm gathering from [the haproxy code](https://github.com/haproxy/haproxy/blob/master/src/cfgparse-listen.c#L159-L220) that there is an order here:

For frontend & listen: (where applicable options are available)
```
tcp-request connection
tcp-request session
tcp-request content
monitor fail
block (deprecated)
http-request
reqxxx
reqadd
redirect
use_backend
```

I tested this locally and was able to get the configuration validation warnings for all scenarios except the ordering related to `monitor fail`. The `block` also complains about being deprecated.

The fix could be just adding some more checks in the template for these other options to output them in the correct order.

**Comment by damacus** [comment]
Is there somewhere in the Haproxy docs we can point to, and maybe crib from to get this sorted?

Or at least have the values we pass on, not break Haproxy by default?

**Comment by JohnRoesler** [comment]
I haven't found it any documentation as of yet. I just sent an email per their repo's docs on contacting them, requesting some info/docs on the ordering of the config.

**Comment by JohnRoesler** [comment]
Nothing documented beyond the code. The order in the initial comment there is the hierarchy then. Thoughts on handling that in the template when any of those `extra_options` are set?

**Comment by damacus** [comment]
I'm really not sure we can do anything smart, apart from not reload Haproxy if the config is wrong in that case.

**Comment by JohnRoesler** [comment]
I was thinking we could do similar to the change I made for `use_backend` and `http-request` and just apply the config values, if set in other options, in the correct order in the template.

**Comment by JohnRoesler** [comment]
I will be opening a new PR to add some documentation around these errors and the specific ordering the values need to be placed in using `extra-options` in lieu of making nasty erb template files.
