### ISSUE TITLE
Fix ChefIgnore

### ISSUE THREAD

**Issue by Xorima** [sous-chefs/haproxy#331]
### Cookbook version
6.2.7

### Scenario:
When downloading the haproxy cookbook from chef supermarket I expect it to only return required files

### Expected Result:
metadata.rb, CONTRIBUTING.md and .foodcritic are not included

### Actual Result:
metadata.rb, CONTRIBUTING.md and .foodcritic are included

**Comment by JohnRoesler** [comment]
All those files are in the chefignore file. Something else is going on here that they're getting uploaded I think

**Comment by damacus** [comment]
I wonder whether stove is listening to the chef ignore file 🤔

**Comment by JohnRoesler** [comment]
@tas50 Any idea what's going on here? If I download the latest cookbook from the super market, the following are present:
```
# Should be
files/
libraries/
metadata.json
README.md
resources/
templates/

# Should not be
.foodcritic
CHANGELOG.md
CONTRIBUTING.md
```

**Comment by tas50** [comment]
How was haproxy uploaded to the supermarket? Stove has it's own whitelist system that ignores the chefignore and knife doesn't use it either.

**Comment by JohnRoesler** [comment]
It was done using stove

**Comment by JohnRoesler** [comment]
Are those files ok to be there? They're just listed in the chefignore, so wasn't expecting

**Comment by Xorima** [comment]
we should probably try to get all these chef tools to have a standard whitelist/ignore system to make life less complicated?

**Comment by JohnRoesler** [comment]
something that will be handled by the auto release bot?
