### ISSUE TITLE
De-Poise this cookbook

### ISSUE THREAD

**Issue by Xorima** [sous-chefs/haproxy#332]
### Cookbook version
Latest

### Scenario:
We should remove poise requirements from this cookbook, it adds a lot of dependencies for this cookbook,

investigate this and see if it is due to OS requirements etc?

**Comment by JohnRoesler** [comment]
dropping poise and moving to systemd only would require us to drop:
- Centos 6
- Redhat 6 (including Oracle Linux 6)
- Amazon 1 (Amazon 2 is good), the metadata suggests we support amazon, readme does not.

**Comment by Xorima** [comment]
True, but poise is also unsupported by CodeRanger so what do we want to do?

**Comment by rshade** [comment]
I don't see a deprecation notice in supermarket or github?

**Comment by Stromweld** [comment]
He has expressed it a few times in the slack channels that he will not be actively maintaining the poise cookbooks due to his current work doesn't have him actively maintaining chef cookbooks anymore.

**Comment by damacus** [comment]
I'm quite keen to drop rhel 6,so probably when 8 goes GA. We can think about dropping it.

Does Amazon still actively point you towards amazon 1, or only 2?

**Comment by damacus** [comment]
Done!

**Comment by JohnRoesler** [comment]
Well done mates!
