### ISSUE TITLE
Add server-template to backend

### ISSUE THREAD

**Issue by michal-sujkowski** [sous-chefs/haproxy#344]
https://www.haproxy.com/blog/whats-new-haproxy-1-8/#dns-for-service-discovery
https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4.2-server-template

**Comment by JohnRoesler** [comment]
hi @michal-sujkowski thanks for submitting an issue. However, you can already use the `server-template` directive using the `extra_options` hash in the `haproxy_backend` resource. The `extra_options` hash can be used to apply any section options that aren't explicitly defined on the resource.

For example:

```
haproxy_backend 'servers' do
  extra_options('server-template' => 'server 3 127.0.0.1:8000 maxconn 32')
end
```
