### ISSUE TITLE
haproxy default package version is 1.5

### ISSUE THREAD

**Issue by JohnRoesler** [sous-chefs/haproxy#348]
### What's the issue
Found this when converging a test recipe so I had a kitchen to play around with. Found out that the default haproxy package install version is 1.5 (confirmed on centos 7, haven't replicated on other platforms yet). 

### Why does it matter
A lot of tests use `haproxy_install 'package'` and 1.5 is `critical patches only`

### What should we do
Explicitly set the haproxy package version

**Comment by JohnRoesler** [comment]
This is the default package version of HAProxy from the centos default repositories. In order to get a later version of HAProxy, one would need to add new repositories. I'm going to remove testing this as it's a false sense of security, and I'm guessing most folks are installing from source on Centos

**Comment by damacus** [comment]
There have been mentions of a mirror for CentOS that would give us newer mirrors for Apache2. THey may well have some for haproxy too...

https://github.com/sous-chefs/apache2/issues/614

**Comment by damacus** [comment]
Looks like IUS might be a good place to crib the service options from

https://github.com/iuscommunity-pkg/haproxy18u/blob/master/SOURCES/haproxy.service

**Comment by JohnRoesler** [comment]
closed by #371 & #372
