### ISSUE TITLE
Haproxy service should only support systemd systems 

### ISSUE THREAD

**Issue by damacus** [sous-chefs/haproxy#355]
We should specify platforms that the resource supports. 
Eg centos 6 isn't a supported platform version

```ruby

provides :my_custom_resource, platform: 'redhat' do |node|
  node['platform_version'].to_i >= 7
end
```

**Comment by rshade** [comment]
Wont #332 fix this?

**Comment by JohnRoesler** [comment]
Partly, I believe. It would fix this in that the OSes will not be supported - but there is the 2nd piece of actually adding the `provides` into all the resource, which wouldn't be done by removing poise.

**Comment by JohnRoesler** [comment]
Done!

**Comment by damacus** [comment]
Reopening so I remember to put that provides block in

**Comment by JohnRoesler** [comment]
we don't need this anymore - we only have systemd service, so no need to provide a `haproxy_service` that maps to `haproxy_service_systemd`
