### ISSUE TITLE
source-default-centos-7 is failing

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/haproxy#358]
### Cookbook version
HEAD as of 2019-03-18

See this build: https://circleci.com/gh/sous-chefs/haproxy/2606

**Comment by rshade** [comment]
C:\GitHub\sous-chefs\haproxy>chef exec kitchen verify source-18-centos-7
-----> Starting Kitchen (v1.23.2)
-----> Setting up <source-18-centos-7>...
       Finished setting up <source-18-centos-7> (0m0.00s).
-----> Verifying <source-18-centos-7>...
       Loaded tests from {:path=>"C:.GitHub.sous-chefs.haproxy.test.integration.source-1.8"}

Profile: tests from {:path=>"C:/GitHub/sous-chefs/haproxy/test/integration/source-1.8"} (tests from {:path=>"C:.GitHub.sous-chefs.haproxy.test.integration.source-1.8"})
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2222

  Directory /etc/haproxy
     [PASS]  should exist
  File /etc/haproxy/haproxy.cfg
     [PASS]  mode should cmp == "0644"
  Service haproxy
     [PASS]  should be installed
     [PASS]  should be enabled
     [PASS]  should be running

Test Summary: 5 successful, 0 failures, 0 skipped
       Finished verifying <source-18-centos-7> (0m3.05s).
-----> Kitchen is finished. (0m50.51s)

**Comment by JohnRoesler** [comment]
Looks like that circle link is to a failure on the de-poise branch, which we're still working on. Master appears to be ok.
