### ISSUE TITLE
Consider running circleci builds on tag instead of merge to master

### ISSUE THREAD

**Issue by JohnRoesler** [sous-chefs/haproxy#376]
The build badge isn't really very useful. We know that master is successful if all the checks in the PR pass. What I, as a user would find more valuable, is if the build badge showed the status of the latests release. I don't care if master is currently failing, because that might just mean new features are being worked on.

**Comment by damacus** [comment]
master should always be releasable. I've we've merged something into master that's broken the build we're bad people

**Comment by JohnRoesler** [comment]
yeah that's fair. I guess I'm just feeling the pain of those constant chef install failures in circle 😞 keep having to restart build jobs to get master to green

**Comment by damacus** [comment]
Ah yeah we need to raise an issue with them, when they're not on fire from everyone migrating from Travis
