### ISSUE TITLE
Multiple bind lines are joined with extraneous colon

### ISSUE THREAD

**Issue by BenOvermyer** [sous-chefs/haproxy#388]
### Cookbook version
7.1.0

### Chef-client version
14.12.9

### Platform Details
CentOS 7 VM

### Scenario:
Specify multiple bind lines in a frontend that do not conform to an "address:port" format

### Steps to Reproduce:
1. Configure a frontend like so:
```
{
  bind: {
    "*:80": "",
    "*:443": "ssl crt /etc/haproxy/site.pem",
    "/var/run/ssl-frontend.sock": "user root mode 600 accept-proxy",
  },
 ...
}
```

### Expected Result:
haproxy.cfg should contain lines like:

```
bind *:80
bind *:443 ssl crt /etc/haproxy/site.pem
bind /var/run/ssl-frontend.sock user root mode 600 accept-proxy
```

### Actual Result:
haproxy.cfg is configured like:

```
bind *:80:
bind *:443: ssl crt /etc/haproxy/site.pem
bind /var/run/ssl-frontend.sock: user root mode 600 accept-proxy
```

**Suggested fix:** Remove the `:` delimiter from the join code for the hash.

**Comment by damacus** [comment]
Hey, 

thanks for the issue. Can you try with hash rockets instead please?

```ruby
{
  bind: {
    "*:80" => "",
    "*:443" => "ssl crt /etc/haproxy/site.pem",
    "/var/run/ssl-frontend.sock" => "user root mode 600 accept-proxy",
  },
 ...
}
```

**Comment by BenOvermyer** [comment]
The same effect occurs using `=>` versus `:` for defining the key -> value relationship.

**Comment by damacus** [comment]
Are you able to drop this configuration into a PR, so we can:
- Add testing
- Debug this in CI

I can't clearly see what's going on here it's a bit odd.

**Comment by BenOvermyer** [comment]
Fairly certain that this is the offending line:

https://github.com/sous-chefs/haproxy/blob/master/resources/frontend.rb#L31

**Comment by damacus** [comment]
Gah, yes. That would be it. Any idea how to make that less terrible I'm all ears!

**Comment by JohnRoesler** [comment]
Thanks for reporting the issue!

The design for the `bind` property it appears was that the key would be the address and the value would be the port. I'm not sure that actually makes much sense in practical use cases. 

I propose we change the `bind` option to `string` or `array` instead of `string` or `hash`.  Or perhaps to be non-breaking we support all three `string,array,hash`

As a work around you could use the `extra_options` has for now like - not you have to set something in bind as well so the default doesn't get applied:

```
haproxy_frontend 'default' do
  bind "*:80"
  extra_options "bind *:443" => "ssl crt /etc/haproxy/site.pem",
                "bind /var/run/ssl-frontend.sock" => "user root mode 600 accept-proxy"
end
```

which renders as desired:

```
frontend default
  bind *:80
  bind *:443 ssl crt /etc/haproxy/site.pem
  bind /var/run/ssl-frontend.sock user root mode 600 accept-proxy
```

**Comment by BenOvermyer** [comment]
@JohnRoesler Thanks for the workaround!

As an alternative to John's proposal, how about this:

The `bind` property still only accepts `string,hash`, but the hash form changes to specify the _whole bind address_ as the key, and any follow-on options as the value. So:

```
haproxy_frontend 'default' do
  bind {
    "*:80": "",
    "*:443": "ssl crt /etc/haproxy/site.pem",
    "/var/run/ssl-frontend.sock": "user root mode 600 accept-proxy"
  }
end
```

This feels more natural to me (and may just be subjective). However, it would be a breaking change from the previous behavior.

**Comment by JohnRoesler** [comment]
Release versions are free 😄 so let's do it the "right" way. I agree with your proposal @BenOvermyer 

Would you like to make a PR for this?

**Comment by BenOvermyer** [comment]
@JohnRoesler Go ahead and implement it; I've got plenty on my plate already, haha. Thank you!

**Comment by JohnRoesler** [comment]
Version 8.0.0 has been released - includes this fix and two new resources added
