### ISSUE TITLE
Leaves server unstable in very specific chef-run failure

### ISSUE THREAD

**Issue by mmranger** [sous-chefs/haproxy#398]
### Cookbook version
8.1.0

### Chef-client version
 tested environment 13.12.14
 our effected environment 14.13.11
(fyi 13.0.113 cannot converge at all)

### Platform Details
tested on centos-7
our ubuntu 16.04 had the problem in the wild

### Scenario:
Chef run failure after some of the resources but not all the resources leaves server in unstable state.  Our particular problem involved intermittent Internet loss to the server (ISP problem). In our haproxy setup cookbook/recipe we set defautls, then globals and during the frontend setup we have another process kick off that requires the Internet. So this partial Internet outage caused the run to fail right there.   Normally a complete Internet error wouldn't even get to this particular point, and not cause this issue.

### Steps to Reproduce:
I threw a cookbook into github with a reproduction https://github.com/mmranger/haproxy_fail.  Essentially converge your test suite on config_1 then verify.  Now add a line around 27 of that test recipe which will break like package 'I will break it' Converge again (it will fail obviously), but then run verify and see the results leave the server in a bad state.  Haproxy is still running but the config file is half full.

### Expected Result:
I can see why this is happening and not sure if (should) can be easily fixed.  But ideally if the chef run fails at any point the haproxy.cfg is not touched.

### Actual Result:
The run changed the haproxy.cfg and had the global and defaults but no front or back ends.  Thus a broken server.

### Workaround
What I did was move the front/backend creation before the global/defaults so if I have this particular (rare) issue it will not change the config at all.  Maybe something in the documentation for the cookbook about this?

**Comment by JohnRoesler** [comment]
@mmranger thanks for reporting the issue. At the very least we can make an addition to the readme regarding this situation and how to protect your setup. 

I will do some investigation to see if there is a way to setup the cookbook to avoid this issue.

**Comment by JohnRoesler** [comment]
Closing this issue - if others report a similar problem we can add some guidance on how to avoid. For now, this issue exists and is searchable.
