### ISSUE TITLE
Haproxy frontend attributes are not showing up

### ISSUE THREAD

**Issue by gangadhar01a** [sous-chefs/haproxy#422]
We are trying to configure following frontend using haproxy cookbook

frontend http
	bind *:80
        option http-keep-alive
	rspidel ^Server:.*$
        rspidel ^X-Powered-By:.*$
        rspidel ^X-AspNet-Version:.*$

Haproxy cookbook is able to reflect all attributes except 2 of the "rspidel".  We have defined "rspidel" related attributes within hash as listed below 

**default['haproxy']['http']['extra_options'] = { 'rspidel' => '^Server:.*$', 'rspidel' => '^X-Powered-By:.*$', 'rspidel' => '^X-AspNet-Version:.*$' }**

**frontend.rb**

  haproxy_frontend frontend do
    bind node['haproxy'][frontend]['bind']
    option node['haproxy'][frontend]['option']
    mode node['haproxy'][frontend]['mode']
    **extra_options node['haproxy'][frontend]['extra_options']**
    acl node['haproxy'][frontend]['acl']
    use_backend node['haproxy'][frontend]['backend']
    default_backend node['haproxy'][frontend]['default_backend']
  end

**Problem:**
After running the chef client I was expecting all of the attributes related to "rspidel" will show up under frontend, instead only "rspidel ^Server:.*$" exist in haproxy. 

**Chef-client resulted in following WARNING's**

/home/ganga/chef-repo/.chef/local-mode-cache/cache/cookbooks/nrhl_haproxy/attributes/erpfcfrontend.rb:37: warning: key "rspidel" is duplicated and overwritten on line 37
/home/ganga/chef-repo/.chef/local-mode-cache/cache/cookbooks/nrhl_haproxy/attributes/erpfcfrontend.rb:37: warning: key "rspidel" is duplicated and overwritten on line 37
/home/ganga/chef-repo/.chef/local-mode-cache/cache/cookbooks/nrhl_haproxy/attributes/erpfcfrontend.rb:48: warning: key "rspidel" is duplicated and overwritten on line 48
/home/ganga/chef-repo/.chef/local-mode-cache/cache/cookbooks/nrhl_haproxy/attributes/erpfcfrontend.rb:48: warning: key "rspidel" is duplicated and overwritten on line 48

CookBook Version: 8.1.1
Chef Client Version: 15.4.45
OS: Centos7

**Comment by JohnRoesler** [comment]
@gangadhar01a only the one attribute is appearing because you're defining the duplicate hash keys of `rspidel`. To achieve what you're trying to do, you can set the value as an array and it will be iterated applying each value to the key as separate lines. This is documented in the readme https://github.com/sous-chefs/haproxy#common-resource-features:

```ruby
default['haproxy']['http']['extra_options'] = {
    'rspidel' => [
        '^Server:.$',
        '^X-Powered-By:.$',
        '^X-AspNet-Version:.*$'
     ]
}
```
result:
```
frontend http
  rspidel ^Server:.$
  rspidel ^X-Powered-By:.$
  rspidel ^X-AspNet-Version:.*$
```
