### ISSUE TITLE
Strange behaviour with haproxy_lb LWRP

### ISSUE THREAD

**Issue by amdprophet** [sous-chefs/haproxy#65]
I'm currently working on a wrapper cookbook that wraps this haproxy cookbook and I've noticed that, at least in test-kitchen, the haproxy_lb LWRP isn't functioning correctly. The `node['haproxy']['listeners']` attribute is unchanged after calling the LWRP.

While trying to debug, I noticed that adding a log line (https://gist.github.com/amdprophet/db1fba1fe4f84fc4b12c#file-lb-rb-L20) fixes the problem. I'm quite unsure of how adding the log line could possibly fix the LWRP; but it did.

Currently using test-kitchen 1.2.1 w/Chef 11.10.4.

The wrapper recipe: https://gist.github.com/amdprophet/508981de036090d3100f

**Comment by calebhailey** [comment]
@slyness: is this still our top priority for cookbook maintenance? Will you have time for this this week?

**Comment by slyness** [comment]
@calebhailey This particular change set has definitely fallen off my immediate to do list. But I am willing to get back at it. I'll review the current state of things this week.

**Comment by damacus** [comment]
I'm going to close this off now as we're working towards a custom resources rewrite. 

If #164 doesn't meet your needs we'd love your feedback.
