### ISSUE TITLE
How do I add auth to the admin interface?

### ISSUE THREAD

**Issue by peterneubauer** [sous-chefs/haproxy#82]
I tried 

```
haproxy_lb 'admin' do
  params({
    'stats realm' => 'Haproxy-Statistics',
    'stats auth' => 'user:pwd'
  })
end
```

in my recipe, but it's not showing up in my admin section which looks like

```
# Set up application listeners here.

listen admin
  bind 0.0.0.0:1337
  mode http
  stats uri /
```

**Comment by damacus** [comment]
@peterneubauer is this still an issue? 

I'd like to look at closing this issue with the next release of the haproxy cookbook. 

It would be useful if you've got an example config you want writing out to disk, as I'm not familiar with this part of haproxy (yet)

**Comment by damacus** [comment]
This should now be covered in the `haproxy_listen` resource from #164 .

If it isn't please feel free to drop us some feedback! :D
